# Generated by Django 6.0.2 on 2026-08-05 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_add_product_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal label, e.g. 'Summer Sale 20%'", max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off (%)'), ('fixed', 'Fixed Amount Off (Ksh)')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Enter 20 for 20% off, or 500 for Ksh 500 off', max_digits=10)),
                ('scope', models.CharField(choices=[('all', 'All Products (Site-wide)'), ('products', 'Specific Products'), ('category', 'Specific Category')], default='all', max_length=20)),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Minimum total quantity in cart for promotion to apply (use >1 for bulk discounts)')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Leave blank to start immediately', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text="Only used when scope is 'Specific Category'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='shop.category')),
                ('products', models.ManyToManyField(blank=True, help_text="Only used when scope is 'Specific Products'", related_name='promotions', to='shop.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.promotion'),
        ),
    ]
