# Generated by Django 6.0.2 on 2026-08-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_add_promotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, default='Timeless Beauty', help_text='Small label above the heading (e.g. "NEW COLLECTION")', max_length=80)),
                ('heading', models.CharField(default='Timeless Elegance,\nCrafted to Shine', help_text='Main heading. Use \\n for a line break.', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='Minimal jewelry for everyday confidence.', help_text='Short line below the heading.', max_length=200)),
                ('pill_1', models.CharField(blank=True, default='Hypoallergenic', max_length=60)),
                ('pill_2', models.CharField(blank=True, default='Water Resistant', max_length=60)),
                ('pill_3', models.CharField(blank=True, default='Tarnish Free', max_length=60)),
                ('cta_primary_text', models.CharField(blank=True, default='Explore Collection', max_length=60)),
                ('cta_primary_url', models.CharField(blank=True, default='#products', max_length=200)),
                ('cta_secondary_text', models.CharField(blank=True, default='Contact Us', max_length=60)),
                ('cta_secondary_url', models.CharField(blank=True, default='https://wa.me/254700840182', max_length=200)),
                ('bg_color', models.CharField(blank=True, default='#faf7f4', help_text='CSS colour for the left panel background (e.g. #faf7f4)', max_length=20)),
                ('image_url', models.URLField(blank=True, help_text='External URL for the right-hand hero image', max_length=500)),
                ('image', models.ImageField(blank=True, help_text='Or upload an image', null=True, upload_to='banners/')),
                ('color_scheme', models.CharField(choices=[('light', 'Light (dark text)'), ('dark', 'Dark (light text)')], default='light', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = higher priority when multiple banners are active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
