# Generated by Django 6.0.2 on 2026-08-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_add_hero_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='bg_image',
            field=models.ImageField(blank=True, help_text='Or upload a background image', null=True, upload_to='banners/bg/'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='bg_image_url',
            field=models.URLField(blank=True, help_text='Full-hero background image URL (covers both columns). Overrides bg_color.', max_length=500),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='hide_side_image',
            field=models.BooleanField(default=False, help_text='Hide the right-hand image panel (full-width content)'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(blank=True, help_text='Or upload a side image', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image_url',
            field=models.URLField(blank=True, help_text='Right-hand side image URL', max_length=500),
        ),
    ]
