# Generated by Django 6.0.2 on 2026-08-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_hero_bg_and_hide_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='btn_primary_bg',
            field=models.CharField(blank=True, default='#1a1a1a', help_text='Primary button background colour', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='btn_primary_text_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Primary button text colour', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='btn_secondary_bg',
            field=models.CharField(blank=True, default='transparent', help_text='Secondary button background colour', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='btn_secondary_text_color',
            field=models.CharField(blank=True, default='#1a1a1a', help_text='Secondary button text & border colour', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='heading_color',
            field=models.CharField(blank=True, default='#1a1a1a', help_text='Heading (h1) text colour', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='pill_1_icon',
            field=models.CharField(blank=True, choices=[('check', '✓ Checkmark'), ('shield', '🛡 Shield'), ('star', '★ Star'), ('heart', '♥ Heart'), ('leaf', '🌿 Leaf'), ('diamond', '◆ Diamond'), ('droplet', '💧 Droplet'), ('circle', '○ Circle')], default='shield', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='pill_2_icon',
            field=models.CharField(blank=True, choices=[('check', '✓ Checkmark'), ('shield', '🛡 Shield'), ('star', '★ Star'), ('heart', '♥ Heart'), ('leaf', '🌿 Leaf'), ('diamond', '◆ Diamond'), ('droplet', '💧 Droplet'), ('circle', '○ Circle')], default='droplet', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='pill_3_icon',
            field=models.CharField(blank=True, choices=[('check', '✓ Checkmark'), ('shield', '🛡 Shield'), ('star', '★ Star'), ('heart', '♥ Heart'), ('leaf', '🌿 Leaf'), ('diamond', '◆ Diamond'), ('droplet', '💧 Droplet'), ('circle', '○ Circle')], default='check', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='pill_icon_color',
            field=models.CharField(blank=True, default='#c9a96e', help_text='Feature pill icon colour', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='pill_text_color',
            field=models.CharField(blank=True, default='#555555', help_text='Feature pill label colour', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='subtitle_color',
            field=models.CharField(blank=True, default='#777777', help_text='Subtitle paragraph colour', max_length=20),
        ),
    ]
