# Generated by Django 6.0.2 on 2026-08-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orderitem_protect_product_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='variants',
            field=models.ManyToManyField(blank=True, help_text="Only used when scope is 'Specific Variants'", related_name='promotions', to='shop.productvariant'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='scope',
            field=models.CharField(choices=[('all', 'All Products (Site-wide)'), ('products', 'Specific Products'), ('category', 'Specific Category'), ('variants', 'Specific Variants')], default='all', max_length=20),
        ),
    ]
