# Generated by Django 6.0.2 on 2026-08-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_promotion_variant_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='also_discount_base',
            field=models.BooleanField(default=False, help_text="When scope is 'Specific Variants', also apply the discount to the base product price"),
        ),
    ]
