# Generated by Django 6.0.2 on 2026-08-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_promotion_also_discount_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured products are highlighted in the storefront'),
        ),
    ]
