# Generated by Django 6.0.2 on 2026-08-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited stock. Only used when the product has no variants.', null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited stock.', null=True),
        ),
    ]
