# Generated by Django 6.0.2 on 2026-08-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_herobanner_custom_icon_paths'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['id']},
        ),
        migrations.RemoveConstraint(
            model_name='attribute',
            name='unique_attribute_per_product',
        ),
        migrations.RemoveConstraint(
            model_name='attributevalue',
            name='unique_value_per_attribute',
        ),
        migrations.RemoveConstraint(
            model_name='variantattributevalue',
            name='unique_variant_attribute_value',
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='pill_1_icon_custom',
            field=models.CharField(blank=True, default='', help_text='SVG <path> / <polyline> etc. content when icon is set to Custom', max_length=1000),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='pill_2_icon_custom',
            field=models.CharField(blank=True, default='', help_text='SVG <path> / <polyline> etc. content when icon is set to Custom', max_length=1000),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='pill_3_icon_custom',
            field=models.CharField(blank=True, default='', help_text='SVG <path> / <polyline> etc. content when icon is set to Custom', max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('product', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='variantattributevalue',
            unique_together={('variant', 'attribute_value')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='shop_catego_name_289c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='herobanner',
            index=models.Index(fields=['is_active'], name='shop_heroba_is_acti_1f819e_idx'),
        ),
        migrations.AddIndex(
            model_name='herobanner',
            index=models.Index(fields=['order'], name='shop_heroba_order_f22580_idx'),
        ),
        migrations.AddIndex(
            model_name='herobanner',
            index=models.Index(fields=['created_at'], name='shop_heroba_created_39ca3a_idx'),
        ),
        migrations.AddIndex(
            model_name='herobanner',
            index=models.Index(fields=['is_active', 'order'], name='shop_heroba_is_acti_cfd176_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='shop_order_created_86b012_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='shop_order_status_63c2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='shop_order_order_n_db1214_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_name'], name='shop_order_custome_521d66_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='shop_order_status_700268_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at', 'status'], name='shop_order_created_6e8766_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['total_amount'], name='shop_order_total_a_12a84b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['promotion'], name='shop_order_promoti_6040d2_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='shop_orderi_order_i_08c5ca_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='shop_orderi_product_6d8a07_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['variant'], name='shop_orderi_variant_86bfd0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='shop_orderi_order_i_d3fcce_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product_name'], name='shop_orderi_product_624664_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['price'], name='shop_orderi_price_9b260b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['quantity'], name='shop_orderi_quantit_56c57b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='shop_produc_categor_d249e3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='shop_produc_created_ed077b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available'], name='shop_produc_is_avai_fe9ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='shop_produc_is_feat_e938b5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='shop_produc_name_a2070e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='shop_produc_slug_76971b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_available'], name='shop_produc_categor_b360d9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', 'created_at'], name='shop_produc_is_avai_0038ce_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product'], name='shop_produc_product_220f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='shop_produc_sku_e6b8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_available'], name='shop_produc_is_avai_697492_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_available'], name='shop_produc_product_be3d22_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['size'], name='shop_produc_size_2af33b_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['color'], name='shop_produc_color_8bcc94_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['price'], name='shop_produc_price_c444e0_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['stock'], name='shop_produc_stock_d97542_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active'], name='shop_promot_is_acti_d06a33_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['created_at'], name='shop_promot_created_9d6347_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['starts_at'], name='shop_promot_starts__8c6b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['ends_at'], name='shop_promot_ends_at_70d22f_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['scope'], name='shop_promot_scope_b7c225_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['category'], name='shop_promot_categor_569785_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['min_quantity'], name='shop_promot_min_qua_b0c188_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='shop_promot_is_acti_642480_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', 'min_quantity'], name='shop_promot_is_acti_652d02_idx'),
        ),
    ]
