# Generated by Django 6.0.2 on 2026-08-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_add_database_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='eyebrow_color',
            field=models.CharField(blank=True, default='#c0567a', help_text='Eyebrow label text colour', max_length=20),
        ),
    ]
